INSERT INTO `13-连接查询` VALUES (1, 'a');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c');
INSERT INTO `13-连接查询` VALUES (4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 2, 'b');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (1, 'a', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 4, 'd');
INSERT INTO `13-连接查询` VALUES (3, 'c', 4, 'd');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (2, 'b', 2, 'b');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (3, 'c', 3, 'c');
INSERT INTO `13-连接查询` VALUES (20180101, '杜子腾', '计算机科学与工程', '母猪的产后护理', 78);
INSERT INTO `13-连接查询` VALUES (20180101, '杜子腾', '计算机科学与工程', '论萨达姆的战争准备', 88);
INSERT INTO `13-连接查询` VALUES (20180102, '杜琦燕', '计算机科学与工程', '母猪的产后护理', 100);
INSERT INTO `13-连接查询` VALUES (20180102, '杜琦燕', '计算机科学与工程', '论萨达姆的战争准备', 98);
INSERT INTO `13-连接查询` VALUES (20180103, '范统', '软件工程', '母猪的产后护理', 59);
INSERT INTO `13-连接查询` VALUES (20180103, '范统', '软件工程', '论萨达姆的战争准备', 61);
INSERT INTO `13-连接查询` VALUES (20180104, '史珍香', '软件工程', '母猪的产后护理', 55);
INSERT INTO `13-连接查询` VALUES (20180104, '史珍香', '软件工程', '论萨达姆的战争准备', 46);
